name: Go

on:
  push:
  pull_request:

jobs:
  db-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: go fmt
        run: go fmt ./...
        working-directory: db
      - name: Ensure formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files are not formatted"
            exit 1
          fi
          git diff --exit-code
        working-directory: db
      - name: go vet
        run: go vet ./...
        working-directory: db
      - name: go test
        run: go test ./...
        working-directory: db
